/** Famous cars across history — searchable garage catalog. */
export const CAR_CATALOG = [
  { id: 'cybertruck', name: 'Tesla Cybertruck', year: 2024, maker: 'Tesla', style: 'cybertruck', color: 0xb8bcc4 },
  { id: 'model-t', name: 'Ford Model T', year: 1908, maker: 'Ford', style: 'vintage', color: 0x1a1a1a },
  { id: 'model-a', name: 'Ford Model A', year: 1927, maker: 'Ford', style: 'vintage', color: 0x2d5016 },
  { id: 'beetle', name: 'Volkswagen Beetle', year: 1938, maker: 'Volkswagen', style: 'compact', color: 0x4a90d9 },
  { id: 'jeep-willys', name: 'Willys Jeep', year: 1941, maker: 'Willys', style: 'suv', color: 0x4a5d3a },
  { id: 'cadillac-62', name: 'Cadillac Series 62', year: 1948, maker: 'Cadillac', style: 'sedan', color: 0x1c1c1c },
  { id: 'mg-td', name: 'MG TD', year: 1949, maker: 'MG', style: 'sports', color: 0x8b0000 },
  { id: 'citroen-2cv', name: 'Citroën 2CV', year: 1949, maker: 'Citroën', style: 'compact', color: 0x6b8e23 },
  { id: 'chevy-bel-air', name: 'Chevrolet Bel Air', year: 1955, maker: 'Chevrolet', style: 'sedan', color: 0x1e90ff },
  { id: 'ford-thunderbird', name: 'Ford Thunderbird', year: 1955, maker: 'Ford', style: 'sports', color: 0xffffff },
  { id: 'mercedes-300sl', name: 'Mercedes-Benz 300 SL', year: 1954, maker: 'Mercedes-Benz', style: 'sports', color: 0xc0c0c0 },
  { id: 'mini-cooper', name: 'Mini Cooper', year: 1959, maker: 'Austin', style: 'compact', color: 0xb22222 },
  { id: 'jaguar-e-type', name: 'Jaguar E-Type', year: 1961, maker: 'Jaguar', style: 'sports', color: 0x006400 },
  { id: 'vw-bus', name: 'Volkswagen Type 2 Bus', year: 1962, maker: 'Volkswagen', style: 'van', color: 0xdaa520 },
  { id: 'porsche-911', name: 'Porsche 911', year: 1964, maker: 'Porsche', style: 'sports', color: 0x8b4513 },
  { id: 'ford-mustang', name: 'Ford Mustang', year: 1964, maker: 'Ford', style: 'sports', color: 0xcc0000 },
  { id: 'lamborghini-miura', name: 'Lamborghini Miura', year: 1966, maker: 'Lamborghini', style: 'sports', color: 0xffd700 },
  { id: 'camaro', name: 'Chevrolet Camaro', year: 1966, maker: 'Chevrolet', style: 'sports', color: 0xff8c00 },
  { id: 'corvette-stingray', name: 'Chevrolet Corvette Stingray', year: 1968, maker: 'Chevrolet', style: 'sports', color: 0x000080 },
  { id: 'datsun-240z', name: 'Datsun 240Z', year: 1969, maker: 'Datsun', style: 'sports', color: 0xb8860b },
  { id: 'citroen-ds', name: 'Citroën DS', year: 1955, maker: 'Citroën', style: 'sedan', color: 0x2f4f4f },
  { id: 'lancia-stratos', name: 'Lancia Stratos', year: 1973, maker: 'Lancia', style: 'sports', color: 0xffffff },
  { id: 'ferrari-308', name: 'Ferrari 308 GTB', year: 1975, maker: 'Ferrari', style: 'sports', color: 0xff0000 },
  { id: 'bmw-2002', name: 'BMW 2002', year: 1968, maker: 'BMW', style: 'sedan', color: 0x1a1a2e },
  { id: 'delorean', name: 'DeLorean DMC-12', year: 1981, maker: 'DeLorean', style: 'sports', color: 0xc0c0c0 },
  { id: 'honda-civic', name: 'Honda Civic', year: 1972, maker: 'Honda', style: 'compact', color: 0x4682b4 },
  { id: 'toyota-corolla', name: 'Toyota Corolla', year: 1966, maker: 'Toyota', style: 'compact', color: 0xd3d3d3 },
  { id: 'land-cruiser', name: 'Toyota Land Cruiser', year: 1951, maker: 'Toyota', style: 'suv', color: 0x556b2f },
  { id: 'range-rover', name: 'Range Rover Classic', year: 1970, maker: 'Land Rover', style: 'suv', color: 0x2e8b57 },
  { id: 'mercedes-g', name: 'Mercedes-Benz G-Class', year: 1979, maker: 'Mercedes-Benz', style: 'suv', color: 0x000000 },
  { id: 'bmw-m3-e30', name: 'BMW M3 E30', year: 1986, maker: 'BMW', style: 'sports', color: 0x0000cd },
  { id: 'mazda-miata', name: 'Mazda MX-5 Miata', year: 1989, maker: 'Mazda', style: 'sports', color: 0xdc143c },
  { id: 'honda-nsx', name: 'Honda NSX', year: 1990, maker: 'Honda', style: 'sports', color: 0xff0000 },
  { id: 'mclaren-f1', name: 'McLaren F1', year: 1992, maker: 'McLaren', style: 'sports', color: 0xffd700 },
  { id: 'subaru-impreza', name: 'Subaru Impreza WRX', year: 1992, maker: 'Subaru', style: 'sedan', color: 0x00008b },
  { id: 'toyota-supra', name: 'Toyota Supra MK4', year: 1993, maker: 'Toyota', style: 'sports', color: 0xffa500 },
  { id: 'dodge-viper', name: 'Dodge Viper', year: 1992, maker: 'Dodge', style: 'sports', color: 0x8b0000 },
  { id: 'hummer-h1', name: 'Hummer H1', year: 1992, maker: 'AM General', style: 'suv', color: 0x3d4f2f },
  { id: 'ford-f150', name: 'Ford F-150', year: 1975, maker: 'Ford', style: 'truck', color: 0x1a472a },
  { id: 'chevy-silverado', name: 'Chevrolet Silverado', year: 1998, maker: 'Chevrolet', style: 'truck', color: 0x2f4f4f },
  { id: 'dodge-ram', name: 'Ram 1500', year: 1981, maker: 'Ram', style: 'truck', color: 0x000000 },
  { id: 'tesla-roadster', name: 'Tesla Roadster', year: 2008, maker: 'Tesla', style: 'sports', color: 0xb22222 },
  { id: 'tesla-model-s', name: 'Tesla Model S', year: 2012, maker: 'Tesla', style: 'sedan', color: 0x1c1c1c },
  { id: 'tesla-model-3', name: 'Tesla Model 3', year: 2017, maker: 'Tesla', style: 'sedan', color: 0x2f4f4f },
  { id: 'tesla-model-x', name: 'Tesla Model X', year: 2015, maker: 'Tesla', style: 'suv', color: 0x191970 },
  { id: 'tesla-model-y', name: 'Tesla Model Y', year: 2020, maker: 'Tesla', style: 'suv', color: 0x4682b4 },
  { id: 'rivian-r1t', name: 'Rivian R1T', year: 2021, maker: 'Rivian', style: 'truck', color: 0x556b2f },
  { id: 'lucid-air', name: 'Lucid Air', year: 2021, maker: 'Lucid', style: 'sedan', color: 0xe8e8e8 },
  { id: 'bugatti-chiron', name: 'Bugatti Chiron', year: 2016, maker: 'Bugatti', style: 'sports', color: 0x00008b },
  { id: 'koenigsegg-jesko', name: 'Koenigsegg Jesko', year: 2019, maker: 'Koenigsegg', style: 'sports', color: 0xffffff },
  { id: 'porsche-taycan', name: 'Porsche Taycan', year: 2019, maker: 'Porsche', style: 'sports', color: 0x2f4f4f },
  { id: 'ford-gt', name: 'Ford GT', year: 2005, maker: 'Ford', style: 'sports', color: 0x0000ff },
  { id: 'rolls-phantom', name: 'Rolls-Royce Phantom', year: 2003, maker: 'Rolls-Royce', style: 'sedan', color: 0x1a1a1a },
  { id: 'bentley-continental', name: 'Bentley Continental GT', year: 2003, maker: 'Bentley', style: 'sports', color: 0x006400 },
  { id: 'aston-db5', name: 'Aston Martin DB5', year: 1963, maker: 'Aston Martin', style: 'sports', color: 0xc0c0c0 },
  { id: 'lamborghini-aventador', name: 'Lamborghini Aventador', year: 2011, maker: 'Lamborghini', style: 'sports', color: 0xff4500 },
  { id: 'ferrari-laferrari', name: 'Ferrari LaFerrari', year: 2013, maker: 'Ferrari', style: 'sports', color: 0xff0000 },
  { id: 'pagani-huayra', name: 'Pagani Huayra', year: 2011, maker: 'Pagani', style: 'sports', color: 0x708090 },
  { id: 'jeep-wrangler', name: 'Jeep Wrangler', year: 1986, maker: 'Jeep', style: 'suv', color: 0x8fbc8f },
  { id: 'ford-bronco', name: 'Ford Bronco', year: 1966, maker: 'Ford', style: 'suv', color: 0xcd853f },
  { id: 'toyota-hilux', name: 'Toyota Hilux', year: 1968, maker: 'Toyota', style: 'truck', color: 0xffffff },
  { id: 'nissan-gtr', name: 'Nissan GT-R', year: 2007, maker: 'Nissan', style: 'sports', color: 0xc0c0c0 },
  { id: 'audi-quattro', name: 'Audi Quattro', year: 1980, maker: 'Audi', style: 'sports', color: 0xffffff },
  { id: 'volvo-240', name: 'Volvo 240', year: 1974, maker: 'Volvo', style: 'sedan', color: 0x8b7355 },
  { id: 'saab-900', name: 'Saab 900 Turbo', year: 1978, maker: 'Saab', style: 'sedan', color: 0x2f4f4f },
  { id: 'peugeot-205', name: 'Peugeot 205 GTI', year: 1984, maker: 'Peugeot', style: 'compact', color: 0xff0000 },
  { id: 'fiat-500', name: 'Fiat 500', year: 1957, maker: 'Fiat', style: 'compact', color: 0x87ceeb },
  { id: 'alfa-giulia', name: 'Alfa Romeo Giulia', year: 1962, maker: 'Alfa Romeo', style: 'sedan', color: 0x8b0000 },
  { id: 'maserati-ghibli', name: 'Maserati Ghibli', year: 1967, maker: 'Maserati', style: 'sports', color: 0x1a1a1a },
  { id: 'plymouth-barracuda', name: 'Plymouth Barracuda', year: 1964, maker: 'Plymouth', style: 'sports', color: 0x4b0082 },
  { id: 'dodge-charger', name: 'Dodge Charger', year: 1966, maker: 'Dodge', style: 'sedan', color: 0x000000 },
  { id: 'chevy-impala', name: 'Chevrolet Impala', year: 1958, maker: 'Chevrolet', style: 'sedan', color: 0xffffff },
  { id: 'cadillac-escalade', name: 'Cadillac Escalade', year: 1999, maker: 'Cadillac', style: 'suv', color: 0x1a1a1a },
  { id: 'lincoln-navigator', name: 'Lincoln Navigator', year: 1997, maker: 'Lincoln', style: 'suv', color: 0x2f2f2f },
  { id: 'toyota-prius', name: 'Toyota Prius', year: 1997, maker: 'Toyota', style: 'compact', color: 0x4682b4 },
  { id: 'honda-accord', name: 'Honda Accord', year: 1976, maker: 'Honda', style: 'sedan', color: 0x696969 },
  { id: 'hyundai-ioniq5', name: 'Hyundai Ioniq 5', year: 2021, maker: 'Hyundai', style: 'suv', color: 0xd3d3d3 },
  { id: 'kia-ev6', name: 'Kia EV6', year: 2021, maker: 'Kia', style: 'suv', color: 0x2f4f4f },
  { id: 'ford-mach-e', name: 'Ford Mustang Mach-E', year: 2020, maker: 'Ford', style: 'suv', color: 0x8b0000 },
  { id: 'chevy-bolt', name: 'Chevrolet Bolt EV', year: 2016, maker: 'Chevrolet', style: 'compact', color: 0x4169e1 },
  { id: 'bmw-i4', name: 'BMW i4', year: 2021, maker: 'BMW', style: 'sedan', color: 0x1a1a2e },
  { id: 'mercedes-eqs', name: 'Mercedes-Benz EQS', year: 2021, maker: 'Mercedes-Benz', style: 'sedan', color: 0x000000 },
  { id: 'genesis-gv80', name: 'Genesis GV80', year: 2020, maker: 'Genesis', style: 'suv', color: 0x2f4f4f },
  { id: 'polestar-2', name: 'Polestar 2', year: 2020, maker: 'Polestar', style: 'sedan', color: 0x708090 },
  { id: 'vinfast-vf8', name: 'VinFast VF8', year: 2022, maker: 'VinFast', style: 'suv', color: 0x4682b4 },
  { id: 'byd-han', name: 'BYD Han', year: 2020, maker: 'BYD', style: 'sedan', color: 0x1a1a1a },
  { id: 'nio-et7', name: 'NIO ET7', year: 2021, maker: 'NIO', style: 'sedan', color: 0x2f4f4f },
  { id: 'xpeng-p7', name: 'XPeng P7', year: 2020, maker: 'XPeng', style: 'sedan', color: 0x778899 },
  { id: 'renault-5-ev', name: 'Renault 5 E-Tech', year: 2024, maker: 'Renault', style: 'compact', color: 0xffd700 },
  { id: 'vw-id4', name: 'Volkswagen ID.4', year: 2020, maker: 'Volkswagen', style: 'suv', color: 0x2e8b57 },
  { id: 'skoda-enyaq', name: 'Škoda Enyaq', year: 2020, maker: 'Škoda', style: 'suv', color: 0x556b2f },
  { id: 'seat-leon', name: 'SEAT León', year: 1999, maker: 'SEAT', style: 'compact', color: 0xff6347 },
  { id: 'opel-gt', name: 'Opel GT', year: 1968, maker: 'Opel', style: 'sports', color: 0xffd700 },
  { id: 'triumph-spitfire', name: 'Triumph Spitfire', year: 1962, maker: 'Triumph', style: 'sports', color: 0x006400 },
  { id: 'lotus-elise', name: 'Lotus Elise', year: 1996, maker: 'Lotus', style: 'sports', color: 0xffd700 },
  { id: 'caterham-7', name: 'Caterham Seven', year: 1973, maker: 'Caterham', style: 'sports', color: 0xffff00 },
  { id: 'shelby-cobra', name: 'Shelby Cobra', year: 1962, maker: 'Shelby', style: 'sports', color: 0x0000ff },
  { id: 'ford-gt40', name: 'Ford GT40', year: 1964, maker: 'Ford', style: 'sports', color: 0x0000ff },
  { id: 'porsche-917', name: 'Porsche 917', year: 1969, maker: 'Porsche', style: 'sports', color: 0xffd700 },
  { id: 'ferrari-250gto', name: 'Ferrari 250 GTO', year: 1962, maker: 'Ferrari', style: 'sports', color: 0xff0000 },
  { id: 'bugatti-type57', name: 'Bugatti Type 57', year: 1934, maker: 'Bugatti', style: 'vintage', color: 0x1a1a1a },
  { id: 'rolls-silver-ghost', name: 'Rolls-Royce Silver Ghost', year: 1906, maker: 'Rolls-Royce', style: 'vintage', color: 0x2f4f4f },
  { id: 'packard-eight', name: 'Packard Eight', year: 1924, maker: 'Packard', style: 'vintage', color: 0x1a1a1a },
  { id: 'tucker-48', name: 'Tucker 48', year: 1948, maker: 'Tucker', style: 'sedan', color: 0x8b0000 },
  { id: 'studebaker-avanti', name: 'Studebaker Avanti', year: 1962, maker: 'Studebaker', style: 'sports', color: 0x8b4513 },
  { id: 'amc-gremlin', name: 'AMC Gremlin', year: 1970, maker: 'AMC', style: 'compact', color: 0x228b22 },
  { id: 'pontiac-firebird', name: 'Pontiac Firebird', year: 1967, maker: 'Pontiac', style: 'sports', color: 0xff4500 },
  { id: 'buick-riviera', name: 'Buick Riviera', year: 1963, maker: 'Buick', style: 'sedan', color: 0x000080 },
  { id: 'oldsmobile-442', name: 'Oldsmobile 442', year: 1964, maker: 'Oldsmobile', style: 'sedan', color: 0x8b0000 },
  { id: 'isuzu-trooper', name: 'Isuzu Trooper', year: 1981, maker: 'Isuzu', style: 'suv', color: 0x556b2f },
  { id: 'mitsubishi-pajero', name: 'Mitsubishi Pajero', year: 1981, maker: 'Mitsubishi', style: 'suv', color: 0x8b4513 },
  { id: 'suzuki-jimny', name: 'Suzuki Jimny', year: 1970, maker: 'Suzuki', style: 'suv', color: 0x2e8b57 },
  { id: 'daihatsu-copen', name: 'Daihatsu Copen', year: 2002, maker: 'Daihatsu', style: 'compact', color: 0xff69b4 },
  { id: 'proton-saga', name: 'Proton Saga', year: 1985, maker: 'Proton', style: 'compact', color: 0xc0c0c0 },
  { id: 'tata-nano', name: 'Tata Nano', year: 2008, maker: 'Tata', style: 'compact', color: 0xffd700 },
  { id: 'mahindra-thar', name: 'Mahindra Thar', year: 2010, maker: 'Mahindra', style: 'suv', color: 0x8b0000 },
  { id: 'lada-niva', name: 'Lada Niva', year: 1977, maker: 'Lada', style: 'suv', color: 0x2e8b57 },
  { id: 'uaz-469', name: 'UAZ-469', year: 1972, maker: 'UAZ', style: 'suv', color: 0x556b2f },
  { id: 'zastava-yugo', name: 'Zastava Yugo', year: 1980, maker: 'Zastava', style: 'compact', color: 0xff0000 },
  { id: 'trabant', name: 'Trabant 601', year: 1964, maker: 'Trabant', style: 'compact', color: 0x87ceeb },
  { id: 'wartburg-353', name: 'Wartburg 353', year: 1966, maker: 'Wartburg', style: 'sedan', color: 0x8b4513 },
  { id: 'skoda-favorit', name: 'Škoda Favorit', year: 1987, maker: 'Škoda', style: 'compact', color: 0xd3d3d3 },
  { id: 'dacia-logan', name: 'Dacia Logan', year: 2004, maker: 'Dacia', style: 'sedan', color: 0x4682b4 },
  { id: 'geely-coolray', name: 'Geely Coolray', year: 2019, maker: 'Geely', style: 'suv', color: 0x1a1a1a },
  { id: 'great-wall-haval', name: 'Haval H6', year: 2011, maker: 'Haval', style: 'suv', color: 0x2f4f4f },
  { id: 'chery-tiggo', name: 'Chery Tiggo', year: 2005, maker: 'Chery', style: 'suv', color: 0x708090 },
];
